package stericson.busybox;


import java.util.ArrayList;
import java.util.List;

public class Constants {

    public static final String key = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk78EBO78KPQkOCo2SCPqImOv6ViRmY7Vy/" + getMiddle() + getEnd();

    public static final String  ARM = "arm",
                                X86 = "x86",
                                MIPS = "mips";

    private static int
            NONE = 0,
            UPDATE = 1,
            NEW = 2,
            BOTH = 3;

    public static final int UNINSTALL = 0,
            INSTALL = 1,
            CHOOSE = 3,
            CUSTOM_VERSION = 4,
            NORMAL_INSTALL = 5,
            UNINSTALL_CHOICE = 6,
            HANDLESBIN = 8,
            REINSTALL_SBIN = 9;

    public static int updateType = NEW;

    public static final String  EXTRA_BUSYBOX_VERSION = "version",
                                EXTRA_INSTALL_PATH = "path";

    public static String storageLocation = "/data/data/stericson.busybox/files/bb/";
    public static String preparedLocation = "/data/local/";

    public static String[] versions = {"Busybox 1.30.1", "Custom Version"};

    public static List<String> locations = new ArrayList<>();

    public static String[] appletsString = new String[]
            {
                    "[",
                    "[[",
                    "acpid",
                    "adjtimex",
                    "arp",
                    "arping",
                    "ash",
                    "awk",
                    "base64",
                    "basename",
                    "beep",
                    "blkid",
                    "blockdev",
                    "brctl",
                    "bunzip2",
                    "bzcat",
                    "bzip2",
                    "cal",
                    "cat",
                    "catv",
                    "chat",
                    "chattr",
                    "chgrp",
                    "chmod",
                    "chown",
                    "chpst",
                    "chroot",
                    "chrt",
                    "chvt",
                    "cksum",
                    "clear",
                    "cmp",
                    "comm",
                    "conspy",
                    "cp",
                    "cpio",
                    "crond",
                    "crontab",
                    "cttyhack",
                    "cut",
                    "date",
                    "dc",
                    "dd",
                    "deallocvt",
                    "depmod",
                    "devmem",
                    "df",
                    "dhcprelay",
                    "diff",
                    "dirname",
                    "dmesg",
                    "dnsd",
                    "dnsdomainname",
                    "dos2unix",
                    "du",
                    "dumpkmap",
                    "dumpleases",
                    "echo",
                    "ed",
                    "egrep",
                    "eject",
                    "env",
                    "envdir",
                    "envuidgid",
                    "ether-wake",
                    "expand",
                    "expr",
                    "fakeidentd",
                    "false",
                    "fatattr",
                    "fbset",
                    "fbsplash",
                    "fdflush",
                    "fdformat",
                    "fdisk",
                    "fgconsole",
                    "fgrep",
                    "find",
                    "findfs",
                    "flock",
                    "fold",
                    "free",
                    "freeramdisk",
                    "fsck",
                    "fsck.minix",
                    "fstrim",
                    "fsync",
                    "ftpd",
                    "ftpget",
                    "ftpput",
                    "fuser",
                    "getopt",
                    "grep",
                    "groups",
                    "gunzip",
                    "gzip",
                    "hd",
                    "hdparm",
                    "head",
                    "hexdump",
                    "hostid",
                    "hostname",
                    "httpd",
                    "hush",
                    "hwclock",
                    "i2cdetect",
                    "i2cdump",
                    "i2cget",
                    "i2cset",
                    "id",
                    "ifconfig",
                    "ifdown",
                    "ifenslave",
                    "ifplugd",
                    "ifup",
                    "inetd",
                    "init",
                    "insmod",
                    "install",
                    "ionice",
                    "iostat",
                    "ip",
                    "ipaddr",
                    "ipcalc",
                    "ipcrm",
                    "ipcs",
                    "iplink",
                    "iproute",
                    "iprule",
                    "iptunnel",
                    "kbd_mode",
                    "kill",
                    "killall",
                    "killall5",
                    "klogd",
                    "last",
                    "less",
                    "linux32",
                    "linux64",
                    "linuxrc",
                    "ln",
                    "loadfont",
                    "loadkmap",
                    "logger",
                    "logname",
                    "logread",
                    "losetup",
                    "ls",
                    "lsattr",
                    "lsmod",
                    "lsof",
                    "lspci",
                    "lsusb",
                    "lzop",
                    "lzopcat",
                    "makedevs",
                    "man",
                    "md5sum",
                    "mdev",
                    "mesg",
                    "microcom",
                    "mkdir",
                    "mkdosfs",
                    "mke2fs",
                    "mkfifo",
                    "mkfs.ext2",
                    "mkfs.minix",
                    "mkfs.vfat",
                    "mknod",
                    "mkswap",
                    "mktemp",
                    "modinfo",
                    "modprobe",
                    "more",
                    "mount",
                    "mountpoint",
                    "mpstat",
                    "mt",
                    "mv",
                    "nameif",
                    "nanddump",
                    "nandwrite",
                    "nbd-client",
                    "nc",
                    "netstat",
                    "nice",
                    "nmeter",
                    "nohup",
                    "nslookup",
                    "ntpd",
                    "od",
                    "openvt",
                    "patch",
                    "pgrep",
                    "pidof",
                    "ping",
                    "ping6",
                    "pipe_progress",
                    "pivot_root",
                    "pkill",
                    "pmap",
                    "powertop",
                    "printenv",
                    "printf",
                    "ps",
                    "pscan",
                    "pstree",
                    "pwd",
                    "pwdx",
                    "raidautorun",
                    "rdate",
                    "rdev",
                    "readahead",
                    "readlink",
                    "readprofile",
                    "realpath",
                    "renice",
                    "reset",
                    "resize",
                    "rev",
                    "rm",
                    "rmdir",
                    "rmmod",
                    "route",
                    "rpm",
                    "rpm2cpio",
                    "rtcwake",
                    "run-parts",
                    "runlevel",
                    "runsv",
                    "runsvdir",
                    "rx",
                    "script",
                    "scriptreplay",
                    "sed",
                    "seq",
                    "setarch",
                    "setconsole",
                    "setfont",
                    "setkeycodes",
                    "setlogcons",
                    "setserial",
                    "setsid",
                    "setuidgid",
                    "sha1sum",
                    "sha256sum",
                    "sha3sum",
                    "sha512sum",
                    "showkey",
                    "shuf",
                    "slattach",
                    "sleep",
                    "smemcap",
                    "softlimit",
                    "sort",
                    "split",
                    "start-stop-daemon",
                    "stat",
                    "strings",
                    "stty",
                    "sum",
                    "sv",
                    "svlogd",
                    "swapoff",
                    "swapon",
                    "switch_root",
                    "sysctl",
                    "syslogd",
                    "tac",
                    "tail",
                    "tar",
                    "tcpsvd",
                    "tee",
                    "telnet",
                    "telnetd",
                    "test",
                    "tftp",
                    "tftpd",
                    "time",
                    "timeout",
                    "top",
                    "touch",
                    "tr",
                    "traceroute",
                    "traceroute6",
                    "true",
                    "truncate",
                    "tty",
                    "ttysize",
                    "tunctl",
                    "ubiattach",
                    "ubidetach",
                    "ubimkvol",
                    "ubirmvol",
                    "ubirsvol",
                    "ubiupdatevol",
                    "udhcpc",
                    "udhcpd",
                    "udpsvd",
                    "uevent",
                    "umount",
                    "uname",
                    "unexpand",
                    "uniq",
                    "unix2dos",
                    "unlink",
                    "unlzop",
                    "unxz",
                    "unzip",
                    "uptime",
                    "users",
                    "usleep",
                    "uudecode",
                    "uuencode",
                    "vconfig",
                    "vi",
                    "volname",
                    "wall",
                    "watch",
                    "watchdog",
                    "wc",
                    "wget",
                    "which",
                    "who",
                    "whoami",
                    "whois",
                    "xargs",
                    "xz",
                    "xzcat",
                    "yes",
                    "zcat",
                    "zci"
            };

    private static String getMiddle() {
        return "d5xOi1+B1mJEWtHreHxrDw9sdyVaxbd3X/PnFIUQzj2Qk159RMP7p2lIiJ1yYVyifOciVV1f4r2z7llCKMJYCVVe0k";
    }

    private static String getEnd() {
        return "+9P5SVEWZWoV+5QqJqm06pZ12ChsMNUN+3JujIUtiCARVn4wBmCT+eXfHcxmhyVfnE4a+3FlLGYrnCKE2B6AhcHXJXfPaW3K4P6JMDbWGoxO6yM/qPHqsfbsZK45Ooaqs1To2Oe6b7SaaAxAXPGipTCzQ7x8BRnMLkTMoLVDN0ABVlCgYpcWB9HysPALIXstSUWeGnF4WptkAfc34sQZm42DsQIDAQAB";
    }
}
